from pathlib import Path

p = Path('apps/inkubator-api/src/social.ts')
text = p.read_text()
old = """  return events.flatMap((event) => {\n    const projectName = names.get(event.subject_id);\n    if (!projectName) return [];\n    if (event.event_type === 'project.help_beacon.opened') return [{\n      schema_version: 'world.signal.public.v1' as const, signal_id: event.history_event_id, kind: 'HELP_BEACON_OPENED' as const,\n      project_id: event.subject_id, project_name: projectName, truth_state: 'CLAIMED' as const, occurred_at: event.occurred_at.toISOString(),\n    }];\n    if (event.event_type === 'project.assist.accepted') return [{\n      schema_version: 'world.signal.public.v1' as const, signal_id: event.history_event_id, kind: 'ASSIST_ACCEPTED' as const,\n      project_id: event.subject_id, project_name: projectName, truth_state: 'OBSERVED' as const, occurred_at: event.occurred_at.toISOString(),\n    }];\n    return [];\n  });\n}"""
new = """  const signals: Array<{\n    schema_version: 'world.signal.public.v1';\n    signal_id: string;\n    kind: 'HELP_BEACON_OPENED' | 'ASSIST_ACCEPTED';\n    project_id: string;\n    project_name: string;\n    truth_state: 'CLAIMED' | 'OBSERVED';\n    occurred_at: string;\n  }> = [];\n  for (const event of events) {\n    const projectName = names.get(event.subject_id);\n    if (!projectName) continue;\n    if (event.event_type === 'project.help_beacon.opened') {\n      signals.push({schema_version: 'world.signal.public.v1', signal_id: event.history_event_id, kind: 'HELP_BEACON_OPENED', project_id: event.subject_id, project_name: projectName, truth_state: 'CLAIMED', occurred_at: event.occurred_at.toISOString()});\n    } else if (event.event_type === 'project.assist.accepted') {\n      signals.push({schema_version: 'world.signal.public.v1', signal_id: event.history_event_id, kind: 'ASSIST_ACCEPTED', project_id: event.subject_id, project_name: projectName, truth_state: 'OBSERVED', occurred_at: event.occurred_at.toISOString()});\n    }\n  }\n  return signals;\n}"""
if old not in text:
    raise SystemExit('world signal projector anchor missing')
p.write_text(text.replace(old, new, 1))
print('World signal projector typing repaired')
