(()=>{"use strict";
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
const coarse=matchMedia('(pointer:coarse)').matches;
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const sections=$$('[data-section]'),nav=$$('.nav button'),mobileProgress=$('#mobileProgress');
function go(i){$('#s'+i)?.scrollIntoView({behavior:reduced?'auto':'smooth',block:'start'})}
$$('[data-go]').forEach(b=>b.addEventListener('click',()=>go(Number(b.dataset.go))));
const secObs=new IntersectionObserver(es=>es.forEach(e=>{if(!e.isIntersecting)return;const i=Number(e.target.dataset.section);nav.forEach((n,j)=>n.classList.toggle('on',i===j));if(mobileProgress)mobileProgress.style.width=((i+1)/sections.length*100)+'%'}),{threshold:.35});sections.forEach(s=>secObs.observe(s));
const loop=$$('#loop button'),ex=$('#loopExplain');loop.forEach(n=>n.addEventListener('click',()=>{loop.forEach(x=>x.classList.remove('on'));n.classList.add('on');ex.textContent=n.dataset.copy||''}));
const toast=$('#toast');let tt;function showToast(t){toast.textContent=t;toast.classList.add('show');clearTimeout(tt);tt=setTimeout(()=>toast.classList.remove('show'),1450)}
async function cp(t){try{await navigator.clipboard.writeText(t);showToast('COPIED')}catch{showToast('COPY BLOCKED')}}
const one='REKT INK(CUBATOR) = a community build experiment that turns culture into a loop: challenge → ship → flex → reward → repeat.';
const pitch='REKT INK(CUBATOR) // Round 000\n\nI build and run the whole thing. REKT puts up 250 USDT + a few REKT/Chibis, brand approval, official posts and judging weight. We hand-pick 8 founding builders + open 2 wildcard slots, give them 7 days to ship something working, then turn every build into content. Success = 15 enter → 10 ship → 3 slap → 2 stay.';
$('#copyOne').addEventListener('click',()=>cp(one));$('#copyPitch').addEventListener('click',()=>cp(pitch));$('#sharePitch').addEventListener('click',async()=>{if(navigator.share){try{return await navigator.share({title:'REKT INK(CUBATOR)',text:pitch,url:location.href})}catch{}}cp(location.href)});
function lifecycle(canvas,draw,targetFps=30){let raf=0,last=0,visible=true;function tick(t){raf=requestAnimationFrame(tick);if(!visible||document.hidden||t-last<1000/targetFps)return;last=t;draw(t)}const io=new IntersectionObserver(e=>{visible=e[0].isIntersecting;if(visible&&!reduced&&!raf)raf=requestAnimationFrame(tick)},{threshold:.01});io.observe(canvas);document.addEventListener('visibilitychange',()=>{if(document.hidden&&raf){cancelAnimationFrame(raf);raf=0}else if(!document.hidden&&visible&&!reduced&&!raf)raf=requestAnimationFrame(tick)});if(reduced)draw(0);else raf=requestAnimationFrame(tick);return()=>{io.disconnect();if(raf)cancelAnimationFrame(raf)}}
function fitCanvas(c,dprCap){const r=c.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,dprCap);c.width=Math.max(1,Math.round(r.width*d));c.height=Math.max(1,Math.round(r.height*d));const x=c.getContext('2d');x.setTransform(d,0,0,d,0,0);return x}
(function asciiHero(){const c=$('#asciiHero'),x=c.getContext('2d');let px=innerWidth*.76,py=innerHeight*.47,tx=px,ty=py;const glyphs='REKTINK<>[]{}#%+/*01░▒▓';
 function size(){fitCanvas(c,coarse?1.15:1.35)}
 function logoPath(ctx,cx,cy,s){ctx.save();ctx.translate(cx,cy);ctx.scale(s,s);ctx.beginPath();ctx.moveTo(0,-62);ctx.bezierCurveTo(48,-58,67,-20,61,18);ctx.bezierCurveTo(57,51,33,76,0,92);ctx.bezierCurveTo(-33,76,-57,51,-61,18);ctx.bezierCurveTo(-67,-20,-48,-58,0,-62);ctx.closePath();ctx.fill();ctx.restore()}
 function draw(t){const w=c.clientWidth,h=c.clientHeight;px+=(tx-px)*.11;py+=(ty-py)*.11;x.fillStyle='#13061f';x.fillRect(0,0,w,h);const cell=coarse?17:14;const cols=Math.ceil(w/cell)+5,rows=Math.ceil(h/cell)+5,time=t*.001;
  x.textAlign='center';x.textBaseline='middle';x.font=`800 ${Math.max(8,cell*.6)}px ui-monospace,monospace`;
  for(let yy=-3;yy<rows;yy++)for(let xx=-3;xx<cols;xx++){const baseX=xx*cell+(yy%2)*cell*.18,baseY=yy*cell;const drift=((time*(6+(yy%7))+(yy*13))%(cell*5));const gx=baseX,gy=baseY+drift-cell*2.5;const d=Math.hypot(gx-px,gy-py);const influence=Math.max(0,1-d/(coarse?130:170));const noise=(Math.sin(xx*.63+yy*.91+time*.9)+1)*.5;const band=(Math.sin(yy*.32-time*.75)+1)*.5;let a=.17+noise*.21+band*.10+influence*.18;const rare=((xx*13+yy*19)%97===0);let col=influence>.2?`rgba(67,216,255,${Math.min(.78,a)})`:(rare?`rgba(255,122,34,${Math.min(.72,a)})`:`rgba(${150+Math.round(noise*65)},${64+Math.round(noise*35)},${225+Math.round(noise*25)},${Math.min(.62,a)})`);x.save();x.translate(gx,gy);x.rotate(Math.PI/2);x.fillStyle=col;x.fillText(glyphs[Math.abs(xx*17+yy*31+Math.floor(time*7))%glyphs.length],0,0);x.restore()}
  x.save();x.globalCompositeOperation='destination-out';const rg=x.createRadialGradient(px,py,20,px,py,coarse?120:155);rg.addColorStop(0,'rgba(0,0,0,.34)');rg.addColorStop(.62,'rgba(0,0,0,.16)');rg.addColorStop(1,'rgba(0,0,0,0)');x.fillStyle=rg;x.beginPath();x.arc(px,py,coarse?120:155,0,Math.PI*2);x.fill();
  x.fillStyle='rgba(0,0,0,.96)';logoPath(x,px,py-12,coarse?.82:1.02);x.font=`900 ${coarse?30:38}px Arial Black,Arial,sans-serif`;x.textAlign='center';x.textBaseline='middle';x.fillText('REKT',px,py+14);x.restore();
  x.save();x.strokeStyle='rgba(67,216,255,.24)';x.lineWidth=1.4;logoPathStroke(x,px,py-12,coarse?.82:1.02);x.font=`900 ${coarse?30:38}px Arial Black,Arial,sans-serif`;x.textAlign='center';x.textBaseline='middle';x.strokeText('REKT',px,py+14);x.restore();
 }
 function logoPathStroke(ctx,cx,cy,s){ctx.save();ctx.translate(cx,cy);ctx.scale(s,s);ctx.beginPath();ctx.moveTo(0,-62);ctx.bezierCurveTo(48,-58,67,-20,61,18);ctx.bezierCurveTo(57,51,33,76,0,92);ctx.bezierCurveTo(-33,76,-57,51,-61,18);ctx.bezierCurveTo(-67,-20,-48,-58,0,-62);ctx.closePath();ctx.stroke();ctx.restore()}
 c.addEventListener('pointermove',e=>{tx=e.clientX;ty=e.clientY});c.addEventListener('pointerdown',e=>{tx=e.clientX;ty=e.clientY});
 if(coarse&&!reduced){let a=0;setInterval(()=>{a+=.7;tx=innerWidth*(.60+.18*Math.sin(a*.73));ty=Math.min(innerHeight*.72,innerHeight*(.40+.17*Math.cos(a*.51)))},2200)}
 addEventListener('resize',size,{passive:true});size();draw(0);lifecycle(c,draw,coarse?22:30)
})();
(function grain(){const c=$('#grain'),x=c.getContext('2d');function size(){fitCanvas(c,coarse?1.05:1.2)}function draw(t){const w=c.clientWidth,h=c.clientHeight;x.fillStyle='#050307';x.fillRect(0,0,w,h);const count=22;for(let i=0;i<count;i++){const q=i/(count-1),base=h*(.15+.7*q),amp=20+33*Math.sin(q*Math.PI),phase=t*.00032*(.75+q*.55)+i*.39;x.beginPath();for(let xx=-20;xx<=w+20;xx+=8){const yy=base+Math.sin(xx*.012+phase)*amp+Math.sin(xx*.004-phase*.7)*16;xx===-20?x.moveTo(xx,yy):x.lineTo(xx,yy)}const r=Math.round(139+(220-139)*q),g=Math.round(92+(59-92)*q),b=Math.round(246+(234-246)*q);x.strokeStyle=`rgba(${r},${g},${b},${.05+.12*Math.sin(q*Math.PI)})`;x.lineWidth=.7+(i%3)*.14;x.stroke()}for(let i=0;i<Math.floor(w*h/15000);i++){x.fillStyle='rgba(247,242,251,.035)';x.fillRect(Math.random()*w,Math.random()*h,1,1)}}addEventListener('resize',size,{passive:true});size();draw(0);lifecycle(c,draw,coarse?18:24)})();
if(!reduced&&!coarse)$$('.reward').forEach(card=>{card.addEventListener('pointermove',e=>{const r=card.getBoundingClientRect(),u=(e.clientX-r.left)/r.width,v=(e.clientY-r.top)/r.height;card.style.setProperty('--mx',u*100+'%');card.style.setProperty('--my',v*100+'%');card.style.transform=`rotateX(${(0.5-v)*4.5}deg) rotateY(${(u-.5)*6}deg) translateY(-2px)`});card.addEventListener('pointerleave',()=>card.style.transform='')});
})();
