import test from 'node:test';
import assert from 'node:assert/strict';
import {
  BUILD_CONTRACT_SCHEMA_VERSION, MECHANISM_VERSION, SETTLEMENT_POLICY_VERSION, IP_TERMS_VERSION,
  CHALLENGE_STATES, SETTLEMENT_INTENT_TYPES, freezeBuildContract, digestBuildContract, assertFrozenBuildContract,
  canTransitionChallenge, transitionChallenge, validateFundingFact, migrateDraftBuildContract,
  validateEntrySet, activateEntries, publicEntryProjection, assertSubmissionManifest,
  selectFinalSubmission, recordArchiveObservation, computeQualification, appendAppealEvent,
  validateSelection, computeDefaultDistribution, computeDefaultResolution, buildSettlementIntent,
  assertSettlementIntent, assertSettlementIntentMatchesContract, applyFinalizedSettlementFact,
  computeIpTransferFact, fileReceipt, assertReceiptMatchesContract, appendReceiptCorrection,
} from '../src/challenge.mjs';
import {digestRecord} from '../src/index.mjs';

const H = (c) => digestRecord(c);
const t0 = 1_800_000_000_000;
function contract(overrides={}) {
  return {
    schema_version: BUILD_CONTRACT_SCHEMA_VERSION,
    challenge_id: 'CH-1', contract_version: '1', mechanism_version: MECHANISM_VERSION,
    settlement_policy_version: SETTLEMENT_POLICY_VERSION, ip_terms_version: IP_TERMS_VERSION,
    title: 'Build the thing', brief: 'A bounded build.',
    outcome_contract: {criteria:[{id:'OUT-1',description:'Works',mandatory:true}]},
    production_envelope: {criteria:[{id:'ENV-1',description:'Mobile viewport',mandatory:true}]},
    delivery_contract: {criteria:[{id:'DEL-1',description:'Source delivered',mandatory:true}]},
    preferences: {style:'REKT'}, reference_architecture: {stack:['React','Vite']},
    normative_constraints: [{id:'NORM-1',description:'Expose HTTPS',mandatory:true}],
    normative_references: [{id:'REF-1',kind:'FIXTURE',content_digest:'a'.repeat(64),source_url:'https://example.com/frozen'}],
    informational_references: [{id:'INFO-1',url:'https://example.com/live'}],
    knowledge: [{kind:'KNOWN',key:'network',material:true,value:'Ink'}],
    slot_limit:4, activation_minimum:2,
    entry_deadline:t0+100, build_start:t0+100, submission_deadline:t0+1000, appeal_window_ms:200, review_deadline:t0+1800,
    prize_minor_units:1001, prize_display:'1001 units', settlement_asset:'TEST', ...overrides,
  };
}
function frozen(overrides={}) { return freezeBuildContract(contract(overrides)); }
function challenge(status='DRAFT', c=frozen(), extra={}) { return {challenge_id:c.challenge_id,status,contract:c,...extra}; }
function entry(id,builder=id,payout=`pay-${id}`,state='SEATED',extra={}){return {entry_id:id,builder_id:builder,payout_id:payout,state,...extra}}
function manifest(c,e='E1',v=1,accepted=c.submission_deadline-10, overrides={}){
 return {schema_version:'inkubator.submission-manifest/1.0',challenge_id:c.challenge_id,entry_id:e,terms_digest:c.terms_digest,submission_version:v,immutable_source_reference:{kind:'GIT_COMMIT',value:`sha-${v}`},artifact_digest:H({e,v}),evidence_references:[],accepted_at:accepted,...overrides};
}
function finalizedFact(intent, overrides={}) {return {challenge_id:intent.challenge_id,terms_digest:intent.terms_digest,settlement_policy_version:intent.settlement_policy_version,asset:intent.asset,total_minor_units:intent.total_minor_units,recipients:intent.recipients,finality:'FINALIZED',execution_id:'tx-1',...overrides}}

test('B-P020 canonical-equivalent Build Contracts digest identically',()=>{const a=contract();const b={...a,preferences:{style:'REKT'}};assert.equal(digestBuildContract(a),digestBuildContract(b))});
test('B-P021 semantic frozen-field change changes digest',()=>{assert.notEqual(digestBuildContract(contract()),digestBuildContract(contract({slot_limit:5})))});
test('B-P022 normative reference digest changes terms digest',()=>{const a=contract();const b=contract({normative_references:[{...a.normative_references[0],content_digest:'b'.repeat(64)}]});assert.notEqual(digestBuildContract(a),digestBuildContract(b))});
test('B-P023 informational URL is frozen but is not normative qualification input',()=>{const a=frozen({informational_references:[{id:'I',url:'https://example.com/a'}]});const b=frozen({informational_references:[{id:'I',url:'https://example.com/b'}]});assert.notEqual(a.terms_digest,b.terms_digest);const results=['OUT-1','ENV-1','DEL-1','NORM-1'].map(criterion_id=>({criterion_id,result:'PASS'}));assert.equal(computeQualification(a,results).overall,'QUALIFIED');assert.equal(computeQualification(b,results).overall,'QUALIFIED')});
test('B-P027 material unknown blocks freeze',()=>assert.throws(()=>freezeBuildContract(contract({knowledge:[{kind:'UNKNOWN',key:'traffic',material:true}]})),/material UNKNOWN/));
test('B-P034 unsupported version fails closed',()=>assert.throws(()=>freezeBuildContract(contract({mechanism_version:'future/99'})),/unsupported mechanism/));
test('B-P004 frozen contract detects semantic mutation',()=>{const c={...frozen(),title:'changed'};assert.throws(()=>assertFrozenBuildContract(c),/terms_digest/)});
test('B-P035 draft migration only works before liabilities',()=>{const c=contract();const d={challenge_id:c.challenge_id,status:'DRAFT',contract:c};assert.equal(migrateDraftBuildContract(d,{title:'New'}).contract.title,'New');assert.throws(()=>migrateDraftBuildContract({...d,status:'ENTRY_OPEN'},{title:'No'}),/only DRAFT/)});
test('B-P103 undeclared Build Contract fields fail closed',()=>assert.throws(()=>freezeBuildContract(contract({surprise:true})),/undeclared property/));
test('invalid informational URI fails closed',()=>assert.throws(()=>freezeBuildContract(contract({informational_references:[{id:'I',url:'not uri'}]})),/absolute URI/));

const EDGES = new Set(['DRAFT>AWAITING_FUNDING','AWAITING_FUNDING>FUNDED','FUNDED>ENTRY_OPEN','ENTRY_OPEN>NOT_ACTIVATED','ENTRY_OPEN>BUILDING','NOT_ACTIVATED>SETTLEMENT_PENDING','BUILDING>SUBMISSIONS_LOCKED','SUBMISSIONS_LOCKED>QUALIFICATION','QUALIFICATION>APPEAL_WINDOW','APPEAL_WINDOW>FINAL_QUALIFIERS','FINAL_QUALIFIERS>SELECTION','FINAL_QUALIFIERS>SETTLEMENT_PENDING','SELECTION>SETTLEMENT_PENDING','SELECTION>DEFAULT_RESOLUTION','DEFAULT_RESOLUTION>SETTLEMENT_PENDING','SETTLEMENT_PENDING>SETTLED','SETTLED>RECEIPT_FILED']);
test('B-P001 canTransition exposes exactly the declared lifecycle edges',()=>{for(const a of CHALLENGE_STATES)for(const b of CHALLENGE_STATES)assert.equal(canTransitionChallenge(a,b),EDGES.has(`${a}>${b}`),`${a}>${b}`)});
test('funding fact must match amount, asset and contract digest',()=>{const c=contract();const fact={status:'CONFIRMED',challenge_id:c.challenge_id,asset:c.settlement_asset,amount_minor_units:c.prize_minor_units,contract_digest:digestBuildContract(c)};assert.equal(validateFundingFact(c,fact),fact);assert.throws(()=>validateFundingFact(c,{...fact,amount_minor_units:1}),/amount mismatch/)});
test('B-P003 ENTRY_OPEN requires frozen valid contract and pre-deadline now',()=>{const c=frozen();const out=transitionChallenge(challenge('FUNDED',c),'ENTRY_OPEN',{now:c.entry_deadline-1});assert.equal(out.status,'ENTRY_OPEN');assert.throws(()=>transitionChallenge(challenge('FUNDED',c),'ENTRY_OPEN',{now:c.entry_deadline}),/at\/after/)});
test('B-P005/B-P006 activation minimum controls ENTRY_OPEN due transition',()=>{const c=frozen();assert.throws(()=>transitionChallenge(challenge('ENTRY_OPEN',c),'BUILDING',{now:c.entry_deadline,activeSeatCount:1}),/minimum not met/);assert.equal(transitionChallenge(challenge('ENTRY_OPEN',c),'NOT_ACTIVATED',{now:c.entry_deadline,activeSeatCount:1}).status,'NOT_ACTIVATED');assert.equal(transitionChallenge(challenge('ENTRY_OPEN',c),'BUILDING',{now:c.entry_deadline,activeSeatCount:2}).status,'BUILDING')});
test('B-P008 submission lock cannot occur early',()=>{const c=frozen();assert.throws(()=>transitionChallenge(challenge('BUILDING',c),'SUBMISSIONS_LOCKED',{now:c.submission_deadline-1}),/not reached/)});
test('appeal gets its full frozen duration from actual opening time',()=>{const c=frozen();const opened=transitionChallenge(challenge('QUALIFICATION',c),'APPEAL_WINDOW',{now:t0+1500,allFirstPassComplete:true});assert.equal(opened.appeal_opened_at,t0+1500);assert.throws(()=>transitionChallenge(opened,'FINAL_QUALIFIERS',{now:t0+1699,appealsResolved:true}),/not elapsed/);assert.equal(transitionChallenge(opened,'FINAL_QUALIFIERS',{now:t0+1700,appealsResolved:true}).status,'FINAL_QUALIFIERS')});
test('B-P009 zero qualifiers cannot enter subjective selection',()=>{const c=frozen();assert.throws(()=>transitionChallenge(challenge('FINAL_QUALIFIERS',c),'SELECTION',{finalQualifierIds:[]}),/at least one/)});
test('B-P011 review deadline selects default path only after deadline',()=>{const c=frozen();assert.throws(()=>transitionChallenge(challenge('SELECTION',c),'DEFAULT_RESOLUTION',{now:c.review_deadline-1}),/not reached/);assert.equal(transitionChallenge(challenge('SELECTION',c),'DEFAULT_RESOLUTION',{now:c.review_deadline,hasValidSelection:false}).status,'DEFAULT_RESOLUTION')});

test('B-P040 duplicate builder and payout identities fail closed',()=>{assert.throws(()=>validateEntrySet([entry('E1','B1','P1'),entry('E2','B1','P2')]),/builder ids/);assert.throws(()=>validateEntrySet([entry('E1','B1','P1'),entry('E2','B2','P1')]),/payout ids/)});
test('B-P045 organizer cannot occupy builder seat',()=>assert.throws(()=>validateEntrySet([entry('E1','ORG','P1')],{organizerBuilderId:'ORG'}),/organizer/));
test('B-P041/B-P007 activation is order independent and shares times',()=>{const c=frozen();const a=activateEntries([entry('E2'),entry('E1')],c);const b=activateEntries([entry('E1'),entry('E2')],c);assert.deepEqual(a,b);assert.ok(a.every(x=>x.build_start===c.build_start&&x.submission_deadline===c.submission_deadline))});
test('B-P042 withdrawn pre-build seat does not count for activation',()=>{const c=frozen();assert.throws(()=>activateEntries([entry('E1'),entry('E2','E2','P2','WITHDRAWN_PRE_BUILD')],c),/minimum not met/)});
test('active forged entry without canonical times fails closed',()=>assert.throws(()=>validateEntrySet([entry('E1','B1','P1','ACTIVE')]),/requires build_start/));
test('B-P044 pre-reveal projection seals builder and payout identity',()=>{const p=publicEntryProjection(entry('E1','SECRET','PAY'));assert.deepEqual(p,{entry_id:'E1',state:'SEATED'})});

test('B-P050 accepted-before-deadline manifest remains final independent of archive state',()=>{const c=frozen();const m=manifest(c);assert.equal(selectFinalSubmission([m],c,'E1').submission_version,1);const obs=recordArchiveObservation(m,'PLATFORM_UNAVAILABLE','github down');assert.equal(obs.accepted_at,m.accepted_at)});
test('B-P051 accepted-after-deadline never becomes final',()=>{const c=frozen();assert.equal(selectFinalSubmission([manifest(c,'E1',1,c.submission_deadline+1)],c,'E1'),null)});
test('B-P052/B-P053 latest valid manifest wins and invalid later cannot displace it',()=>{const c=frozen();const one=manifest(c,'E1',1,c.submission_deadline-20);const two=manifest(c,'E1',2,c.submission_deadline-10);const bad={...manifest(c,'E1',3,c.submission_deadline-1),artifact_digest:'bad'};assert.equal(selectFinalSubmission([one,bad,two],c,'E1').submission_version,2)});
test('B-P055 wrong terms digest invalidates submission',()=>{const c=frozen();assert.equal(selectFinalSubmission([{...manifest(c),terms_digest:'b'.repeat(64)}],c,'E1'),null)});
test('B-P054 mutable URL alone cannot satisfy immutable identity',()=>{const c=frozen();const m=manifest(c);delete m.immutable_source_reference;assert.throws(()=>assertSubmissionManifest(m),/immutable_source_reference/)});
test('B-P056 wrong challenge and entry identities invalidate submission',()=>{const c=frozen();assert.equal(selectFinalSubmission([{...manifest(c),challenge_id:'OTHER'}],c,'E1'),null);assert.equal(selectFinalSubmission([{...manifest(c),entry_id:'OTHER'}],c,'E1'),null)});
test('B-P058 archive observations distinguish builder revocation from platform outage',()=>{const c=frozen();const m=manifest(c);assert.notEqual(recordArchiveObservation(m,'BUILDER_REVOKED').archive_state,recordArchiveObservation(m,'PLATFORM_UNAVAILABLE').archive_state)});

test('B-P060/B-P061 qualification requires every frozen mandatory criterion exactly once',()=>{const c=frozen();const pass=['OUT-1','ENV-1','DEL-1','NORM-1'].map(criterion_id=>({criterion_id,result:'PASS'}));assert.equal(computeQualification(c,pass).overall,'QUALIFIED');assert.equal(computeQualification(c,pass.map((x,i)=>i===1?{...x,result:'FAIL'}:x)).overall,'NOT_QUALIFIED');assert.equal(computeQualification(c,pass.map((x,i)=>i===1?{...x,result:'DISPUTED'}:x)).overall,'DISPUTED');assert.throws(()=>computeQualification(c,[...pass,{criterion_id:'NEW',result:'PASS'}]),/exactly match/)});
test('B-P062 preferences never participate in qualification',()=>{const c1=frozen({preferences:{style:'A'}});const c2=frozen({preferences:{style:'B'}});const r=['OUT-1','ENV-1','DEL-1','NORM-1'].map(criterion_id=>({criterion_id,result:'PASS'}));assert.equal(computeQualification(c1,r).overall,computeQualification(c2,r).overall)});
test('B-P063 injected hidden criterion metadata fails closed',()=>{const c=frozen();const r=['OUT-1','ENV-1','DEL-1','NORM-1'].map(criterion_id=>({criterion_id,result:'PASS'}));assert.throws(()=>computeQualification(c,[{...r[0],new_requirement:'secret'},...r.slice(1)]),/undeclared property/)});
test('B-P066 appeal budget is exactly one appeal and one resolution',()=>{const a=appendAppealEvent([],{type:'APPEAL',reason:'evidence'});assert.throws(()=>appendAppealEvent(a,{type:'APPEAL',reason:'again'}),/exhausted/);const r=appendAppealEvent(a,{type:'RESOLUTION',result:'PASS'});assert.equal(r.length,2);assert.throws(()=>appendAppealEvent(r,{type:'RESOLUTION'}),/requires exactly/)});
test('B-P067 appeal cannot smuggle a new requirement under an arbitrary key',()=>assert.throws(()=>appendAppealEvent([],{type:'APPEAL',reason:'x',criterion_definition:'new'}),/undeclared property/));
test('B-P010 selection must be a final qualifier',()=>assert.throws(()=>validateSelection('E3',['E1','E2']),/not a final qualifier/));

test('B-P070/B-P071/B-P072 default resolution has 0/1/many deterministic semantics',()=>{assert.equal(computeDefaultResolution([],10).type,'REFUND_NO_QUALIFIER');assert.deepEqual(computeDefaultResolution(['E1'],10),{type:'WINNER_PAYOUT',winner_entry_id:'E1',distributions:[{entry_id:'E1',amount_minor_units:10}]});assert.equal(computeDefaultResolution(['E1','E2'],10).type,'DEFAULT_DISTRIBUTION')});
test('B-P073/B-P074/B-P075/B-P077 default distribution conserves units and order',()=>{for(let n=2;n<=8;n++)for(let prize=0;prize<40;prize++){const ids=Array.from({length:n},(_,i)=>`E${i}`);const a=computeDefaultDistribution(prize,ids);const b=computeDefaultDistribution(prize,[...ids].reverse());assert.deepEqual(a,b);assert.equal(a.reduce((s,x)=>s+x.amount_minor_units,0),prize);assert.ok(Math.max(...a.map(x=>x.amount_minor_units))-Math.min(...a.map(x=>x.amount_minor_units))<=1)}});

test('B-P104 unknown settlement intent types fail closed',()=>{const c=frozen();assert.throws(()=>buildSettlementIntent({contract:c,resolution:{type:'YOLO',winner_entry_id:null,distributions:[]},refundRecipientId:'ORG'}),/unknown settlement intent type/);const legitimate=buildSettlementIntent({contract:c,resolution:computeDefaultResolution(['E1'],c.prize_minor_units),recipientByEntryId:{E1:'A'}});assert.throws(()=>assertSettlementIntent({...legitimate,type:'YOLO'}),/unknown settlement intent type/)});
test('B-P080/B-P081 settlement intent is not execution and mismatches fail closed',()=>{const c=frozen();const resolution=computeDefaultResolution(['E1'],c.prize_minor_units);const intent=buildSettlementIntent({contract:c,resolution,recipientByEntryId:{E1:'0xabc'}});assert.equal(computeIpTransferFact(intent,finalizedFact(intent)),'TRANSFER_TRIGGERED');assert.throws(()=>applyFinalizedSettlementFact(intent,finalizedFact(intent,{asset:'WRONG'})),/does not match/);assert.throws(()=>applyFinalizedSettlementFact(intent,{...finalizedFact(intent),finality:'PENDING'}),/not finalized/)});
test('forged winner payout shape cannot trigger IP transfer',()=>{const c=frozen();const legitimate=buildSettlementIntent({contract:c,resolution:computeDefaultResolution(['E1'],c.prize_minor_units),recipientByEntryId:{E1:'A'}});const forged={...legitimate,winner_entry_id:null};assert.throws(()=>computeIpTransferFact(forged,finalizedFact(forged)),/winner_entry_id/)});
test('receipt and SETTLED transition bind settlement intent to exact frozen contract',()=>{const a=frozen();const b=frozen({challenge_id:'CH-2'});const intentB=buildSettlementIntent({contract:b,resolution:computeDefaultResolution(['E1'],b.prize_minor_units),recipientByEntryId:{E1:'B'}});const factB=finalizedFact(intentB);assert.throws(()=>assertSettlementIntentMatchesContract(a,intentB),/Challenge mismatch/);assert.throws(()=>fileReceipt({contract:a,settlementIntent:intentB,settlementExecutionFact:factB}),/Challenge mismatch/);assert.throws(()=>transitionChallenge(challenge('SETTLEMENT_PENDING',a),'SETTLED',{settlementIntent:intentB,executionFact:factB}),/Challenge mismatch/)});
test('B-P088 multi-qualifier default distribution never triggers IP transfer',()=>{const c=frozen();const resolution=computeDefaultResolution(['E2','E1'],c.prize_minor_units);const intent=buildSettlementIntent({contract:c,resolution,recipientByEntryId:{E1:'A',E2:'B'}});assert.equal(computeIpTransferFact(intent,finalizedFact(intent)),'NOT_TRIGGERED')});
test('B-P086 pre-build refund never triggers IP transfer',()=>{const c=frozen();const intent=buildSettlementIntent({contract:c,resolution:{type:'REFUND_PRE_BUILD',winner_entry_id:null,distributions:[]},refundRecipientId:'ORG'});assert.equal(computeIpTransferFact(intent,finalizedFact(intent)),'NOT_TRIGGERED')});
test('B-P089 finalized settlement replay is idempotent and conflicts reject',()=>{const c=frozen();const intent=buildSettlementIntent({contract:c,resolution:computeDefaultResolution(['E1'],c.prize_minor_units),recipientByEntryId:{E1:'A'}});const fact=finalizedFact(intent);const first=applyFinalizedSettlementFact(intent,fact);assert.equal(applyFinalizedSettlementFact(intent,fact,first),first);assert.throws(()=>applyFinalizedSettlementFact(intent,{...fact,execution_id:'tx-2'},first),/conflicting/)});
test('B-P091/B-P092 receipt filing is deterministic and references frozen versions',()=>{const c=frozen();const intent=buildSettlementIntent({contract:c,resolution:computeDefaultResolution(['E1'],c.prize_minor_units),recipientByEntryId:{E1:'A'}});const fact=finalizedFact(intent);const a=fileReceipt({contract:c,settlementIntent:intent,settlementExecutionFact:fact});const b=fileReceipt({contract:c,settlementIntent:intent,settlementExecutionFact:fact});assert.deepEqual(a,b);assert.equal(a.terms_digest,c.terms_digest);assert.equal(a.ip_transfer_fact,'TRANSFER_TRIGGERED');assert.equal(assertReceiptMatchesContract(c,a),a)});
test('RECEIPT_FILED transition rejects receipt from another Challenge',()=>{const c=frozen();const other=frozen({challenge_id:'CH-X'});const i=buildSettlementIntent({contract:other,resolution:computeDefaultResolution(['E1'],other.prize_minor_units),recipientByEntryId:{E1:'A'}});const r=fileReceipt({contract:other,settlementIntent:i,settlementExecutionFact:finalizedFact(i)});assert.throws(()=>transitionChallenge(challenge('SETTLED',c),'RECEIPT_FILED',{receipt:r}),/Challenge mismatch/)});
test('B-P094/B-P095 receipt correction appends without rewriting money or frozen terms',()=>{const c=frozen();const intent=buildSettlementIntent({contract:c,resolution:computeDefaultResolution(['E1'],c.prize_minor_units),recipientByEntryId:{E1:'A'}});const r=fileReceipt({contract:c,settlementIntent:intent,settlementExecutionFact:finalizedFact(intent)});const correction=appendReceiptCorrection([r],{supersedes:r.receipt_id,reason:'display typo',authority:'resolver',corrected_projection:{title:'fixed'}});assert.equal(correction.supersedes,r.receipt_id);assert.throws(()=>appendReceiptCorrection([r],{supersedes:r.receipt_id,reason:'no',authority:'resolver',corrected_projection:{terms_digest:'b'.repeat(64)}}),/cannot rewrite/)});
test('B-P096 malformed correction chain fails closed',()=>{const fake={receipt_id:'C2',supersedes:'MISSING',challenge_id:'CH'};assert.throws(()=>appendReceiptCorrection([fake],{supersedes:'C2',reason:'x',authority:'resolver'}),/missing predecessor/)});

test('B-P002 protocol never requires Date.now for time-sensitive transitions',()=>{const original=Date.now;Date.now=()=>{throw new Error('hidden clock used')};try{const c=frozen();assert.equal(transitionChallenge(challenge('BUILDING',c),'SUBMISSIONS_LOCKED',{now:c.submission_deadline}).status,'SUBMISSIONS_LOCKED')}finally{Date.now=original}});
test('B-P102 integer arithmetic rejects unsafe money',()=>assert.throws(()=>computeDefaultDistribution(Number.MAX_SAFE_INTEGER+1,['E1','E2']),/safe integer/));
test('settlement intent types list remains closed',()=>assert.deepEqual([...SETTLEMENT_INTENT_TYPES],['REFUND_PRE_BUILD','REFUND_NO_QUALIFIER','WINNER_PAYOUT','DEFAULT_DISTRIBUTION','CANCELLED_BY_RESOLUTION']));
