import test from 'node:test';
import assert from 'node:assert/strict';
import {BUILD_CONTRACT_SCHEMA_VERSION,MECHANISM_VERSION,SETTLEMENT_POLICY_VERSION,IP_TERMS_VERSION,freezeBuildContract,computeDefaultResolution,buildSettlementIntent,transitionChallenge,fileReceipt,assertReceiptMatchesContract} from '../src/challenge.mjs';
import {digestRecord} from '../src/index.mjs';
const t0=1_800_000_000_000;
function frozen(){return freezeBuildContract({schema_version:BUILD_CONTRACT_SCHEMA_VERSION,challenge_id:'CH-BIND',contract_version:'1',mechanism_version:MECHANISM_VERSION,settlement_policy_version:SETTLEMENT_POLICY_VERSION,ip_terms_version:IP_TERMS_VERSION,title:'Bind',brief:'Bind',outcome_contract:{criteria:[]},production_envelope:{criteria:[]},delivery_contract:{criteria:[]},preferences:{},reference_architecture:{},normative_constraints:[],normative_references:[],informational_references:[],knowledge:[],slot_limit:3,activation_minimum:1,entry_deadline:t0+10,build_start:t0+10,submission_deadline:t0+20,appeal_window_ms:10,review_deadline:t0+40,prize_minor_units:1001,settlement_asset:'TEST'});}
function challenge(status,c){return{challenge_id:c.challenge_id,status,contract:c};}
function fact(intent){return{challenge_id:intent.challenge_id,terms_digest:intent.terms_digest,settlement_policy_version:intent.settlement_policy_version,asset:intent.asset,total_minor_units:intent.total_minor_units,recipients:intent.recipients,finality:'FINALIZED',execution_id:'tx'}}

test('targeted: selected payout is bound to actual selected qualifier',()=>{const c=frozen();const intent=buildSettlementIntent({contract:c,resolution:{type:'WINNER_PAYOUT',winner_entry_id:'E1',distributions:[{entry_id:'E1',amount_minor_units:c.prize_minor_units}]},recipientByEntryId:{E1:'A',E2:'B'}});assert.equal(transitionChallenge(challenge('SELECTION',c),'SETTLEMENT_PENDING',{settlementIntent:intent,selectedEntryId:'E1',finalQualifierIds:['E1','E2'],recipientByEntryId:{E1:'A',E2:'B'}}).status,'SETTLEMENT_PENDING');assert.throws(()=>transitionChallenge(challenge('SELECTION',c),'SETTLEMENT_PENDING',{settlementIntent:intent,selectedEntryId:'E2',finalQualifierIds:['E1','E2'],recipientByEntryId:{E1:'A',E2:'B'}}),/does not match selected qualifier/)});
test('targeted: default settlement is bound to exact qualifier set and deterministic equal split',()=>{const c=frozen();const resolution=computeDefaultResolution(['E1','E2'],c.prize_minor_units);const intent=buildSettlementIntent({contract:c,resolution,recipientByEntryId:{E1:'A',E2:'B'}});assert.equal(transitionChallenge(challenge('DEFAULT_RESOLUTION',c),'SETTLEMENT_PENDING',{settlementIntent:intent,finalQualifierIds:['E1','E2'],recipientByEntryId:{E1:'A',E2:'B'}}).status,'SETTLEMENT_PENDING');const skewed={...resolution,distributions:[{entry_id:'E1',amount_minor_units:1000},{entry_id:'E2',amount_minor_units:1}]};assert.throws(()=>buildSettlementIntent({contract:c,resolution:skewed,recipientByEntryId:{E1:'A',E2:'B'}}),/deterministic equal split/);assert.throws(()=>transitionChallenge(challenge('DEFAULT_RESOLUTION',c),'SETTLEMENT_PENDING',{settlementIntent:intent,finalQualifierIds:['E1','E2','E3'],recipientByEntryId:{E1:'A',E2:'B',E3:'C'}}),/does not match deterministic default resolution/)});
test('targeted: receipt labels are derived facts, not caller-controlled claims',()=>{const c=frozen();const intent=buildSettlementIntent({contract:c,resolution:computeDefaultResolution(['E1'],c.prize_minor_units),recipientByEntryId:{E1:'A'}});const r=fileReceipt({contract:c,settlementIntent:intent,settlementExecutionFact:fact(intent)});const payload={...r,terminal_outcome:'REFUNDED_NO_QUALIFIER'};delete payload.receipt_id;delete payload.digest;const digest=digestRecord(payload);const forged={...payload,digest,receipt_id:`receipt_${digest}`};assert.throws(()=>assertReceiptMatchesContract(c,forged),/terminal outcome mismatch/)});
