import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {execFileSync} from 'node:child_process';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import test from 'node:test';
import {BUILD_CONTRACT_SCHEMA_VERSION,MECHANISM_VERSION,SETTLEMENT_POLICY_VERSION,IP_TERMS_VERSION,freezeBuildContract} from '@rekt-ink/protocol/challenge';
import {main} from '../dist/cli.js';

const challengeId='11111111-1111-4111-8111-111111111111';
const entryId='33333333-3333-4333-8333-333333333333';
const t0=1_800_000_000_000;
const artifactDigest='a'.repeat(64);
const digest=(value)=>createHash('sha256').update(value,'utf8').digest('hex');
function canon(value){if(Array.isArray(value))return value.map(canon);if(value&&typeof value==='object')return Object.fromEntries(Object.keys(value).sort().map((key)=>[key,canon(value[key])]));return value;}
const canonicalJson=(value)=>JSON.stringify(canon(value));
const criteria=(value)=>Array.isArray(value?.criteria)?value.criteria:[];
function renderCriteria(title,items){const lines=[`## ${title}`,''];return items.length?[...lines,...items.map((item)=>`- [${item.mandatory?'x':' '}] **${item.id}** — ${item.description}`),'']:[...lines,'_No criteria declared._',''];}
function frozenContract(){return freezeBuildContract({schema_version:BUILD_CONTRACT_SCHEMA_VERSION,challenge_id:challengeId,contract_version:'1.0.0',mechanism_version:MECHANISM_VERSION,settlement_policy_version:SETTLEMENT_POLICY_VERSION,ip_terms_version:IP_TERMS_VERSION,title:'Build a dashboard',brief:'Bounded dashboard.',outcome_contract:{criteria:[{id:'OUT-1',description:'Works',mandatory:true}]},production_envelope:{criteria:[]},delivery_contract:{criteria:[]},preferences:{},reference_architecture:{},normative_constraints:[],normative_references:[],informational_references:[],knowledge:[{kind:'KNOWN',key:'network',material:true,value:'Ink'}],slot_limit:4,activation_minimum:2,entry_deadline:t0+100,build_start:t0+100,submission_deadline:t0+1000,appeal_window_ms:200,review_deadline:t0+1800,prize_minor_units:100,settlement_asset:'TEST'});}
function challengeMarkdown(contract){const lines=[`# ${contract.title}`,'','> DERIVED BUILDER VIEW. Canonical authority is `contract.json` and its frozen `terms_digest`.','',`**Challenge:** \`${contract.challenge_id}\`  `,`**Contract:** \`${contract.contract_version}\`  `,`**Terms digest:** \`${contract.terms_digest}\`  `,`**Build starts:** ${new Date(contract.build_start).toISOString()}  `,`**Submission deadline:** ${new Date(contract.submission_deadline).toISOString()}`,'','## Brief','',contract.brief,'',...renderCriteria('Outcome Contract',criteria(contract.outcome_contract)),...renderCriteria('Production Envelope',criteria(contract.production_envelope)),...renderCriteria('Delivery Contract',criteria(contract.delivery_contract)),...renderCriteria('Normative Constraints',contract.normative_constraints??[]),'## References','','_No references declared._','','## Preferences','','Preferences are non-qualifying selection guidance unless the frozen contract says otherwise.','','```json',canonicalJson(contract.preferences),'```','','## Reference Architecture','','Reference architecture is advisory unless a frozen criterion or normative constraint makes a specific interface/technology mandatory.','','```json',canonicalJson(contract.reference_architecture),'```',''];return lines.join('\n');}
function capsule(){const contract=frozenContract();const acceptance={schema_version:'builder-capsule.acceptance.v1',challenge_id:challengeId,terms_digest:contract.terms_digest,criteria:[...criteria(contract.outcome_contract).map((item)=>({section:'OUTCOME',...item}))],executable_checks_authorized:false};const references={schema_version:'builder-capsule.references.v1',challenge_id:challengeId,terms_digest:contract.terms_digest,normative:[],informational:[]};const contents={'CHALLENGE.md':challengeMarkdown(contract),'contract.json':`${canonicalJson(contract)}\n`,'acceptance/manifest.json':`${canonicalJson(acceptance)}\n`,'references/manifest.json':`${canonicalJson(references)}\n`};return {schema_version:'builder-capsule.v1',challenge_id:challengeId,entry_id:entryId,entry_state:'ACTIVE',contract_version:contract.contract_version,terms_digest:contract.terms_digest,submission_deadline:new Date(contract.submission_deadline).toISOString(),files:Object.entries(contents).map(([filePath,content])=>({path:filePath,media_type:filePath.endsWith('.md')?'text/markdown':'application/json',sha256:digest(content),content}))};}
function io(){const out=[];const err=[];return {out,err,adapter:{out:(value)=>out.push(value),err:(value)=>err.push(value)}};}
async function pull(cwd,cap,seen){globalThis.fetch=async(input,init={})=>{seen.push({input:String(input),init});return new Response(JSON.stringify(cap),{status:200,headers:{'content-type':'application/json'}});};const logs=io();assert.equal(await main(['challenge','pull',challengeId,'--api','https://api.test'],{REKT_DEVKIT_TOKEN:'rekt_dk_test'},logs.adapter,cwd),0);return logs;}
function accepted(body){return {schema_version:'challenge.submission.accepted.v1',submission_id:body.submission_id,challenge_id:challengeId,entry_id:entryId,submission_version:String(body.submission_version),terms_digest:body.expected_terms_digest,manifest_digest:'b'.repeat(64),accepted_at:new Date().toISOString(),ship_submission_id:null};}

test('F2 CLI validates local capsule and submits canonical capsule lineage without accepted_at',async()=>{const cwd=fs.mkdtempSync(path.join(os.tmpdir(),'rekt-submit-'));const previous=globalThis.fetch;const seen=[];const cap=capsule();try{await pull(cwd,cap,seen);globalThis.fetch=async(input,init={})=>{seen.push({input:String(input),init});const body=JSON.parse(String(init.body));return new Response(JSON.stringify(accepted(body)),{status:201,headers:{'content-type':'application/json'}});};const logs=io();const source='0123456789abcdef0123456789abcdef01234567';assert.equal(await main(['challenge','submit','--version','1','--artifact-digest',artifactDigest,'--source',source,'--api','https://api.test'],{REKT_DEVKIT_TOKEN:'rekt_dk_test'},logs.adapter,cwd),0);assert.equal(seen.length,2);assert.equal(seen[1].input,`https://api.test/v1/devkit/challenges/${challengeId}/submissions`);assert.equal(seen[1].init.method,'POST');assert.equal(new Headers(seen[1].init.headers).get('authorization'),'Bearer rekt_dk_test');const body=JSON.parse(String(seen[1].init.body));assert.equal(body.entry_id,entryId);assert.equal(body.expected_terms_digest,cap.terms_digest);assert.equal(body.submission_version,1);assert.deepEqual(body.immutable_source_reference,{kind:'GIT_COMMIT',value:source});assert.equal(body.artifact_digest,artifactDigest);assert.deepEqual(body.evidence_references,[]);assert.equal('accepted_at' in body,false);}finally{globalThis.fetch=previous;fs.rmSync(cwd,{recursive:true,force:true});}});

test('F2 CLI persists challenge submission retry identity before a lost response and rejects changed payloads locally',async()=>{const cwd=fs.mkdtempSync(path.join(os.tmpdir(),'rekt-submit-retry-'));const previous=globalThis.fetch;const seen=[];const cap=capsule();let posts=0;try{await pull(cwd,cap,seen);const canonicalBefore=fs.readFileSync(path.join(cwd,'.rekt','challenge','capsule.json'),'utf8');globalThis.fetch=async(input,init={})=>{seen.push({input:String(input),init});const body=JSON.parse(String(init.body));posts+=1;if(posts===1){const retryPath=path.join(cwd,'.rekt','challenge','submission-retry','1.json');assert.equal(fs.existsSync(retryPath),true);const retry=JSON.parse(fs.readFileSync(retryPath,'utf8'));assert.equal(retry.request_id,body.request_id);assert.equal(retry.submission_id,body.submission_id);throw new Error('response_lost_after_commit');}return new Response(JSON.stringify(accepted(body)),{status:201,headers:{'content-type':'application/json'}});};let logs=io();const args=['challenge','submit','--version','1','--artifact-digest',artifactDigest,'--source','0123456789abcdef0123456789abcdef01234567','--api','https://api.test'];assert.equal(await main(args,{REKT_DEVKIT_TOKEN:'rekt_dk_test'},logs.adapter,cwd),1);assert.equal(logs.err.at(-1),'response_lost_after_commit');const firstBody=JSON.parse(String(seen[1].init.body));assert.equal(await main(args,{REKT_DEVKIT_TOKEN:'rekt_dk_test'},io().adapter,cwd),0);const secondBody=JSON.parse(String(seen[2].init.body));assert.equal(secondBody.request_id,firstBody.request_id);assert.equal(secondBody.submission_id,firstBody.submission_id);assert.equal(posts,2);assert.equal(fs.readFileSync(path.join(cwd,'.rekt','challenge','capsule.json'),'utf8'),canonicalBefore);logs=io();assert.equal(await main(['challenge','submit','--version','1','--artifact-digest','c'.repeat(64),'--source','0123456789abcdef0123456789abcdef01234567','--api','https://api.test'],{REKT_DEVKIT_TOKEN:'rekt_dk_test'},logs.adapter,cwd),1);assert.equal(logs.err.at(-1),'challenge_submit_retry_payload_conflict');assert.equal(posts,2);}finally{globalThis.fetch=previous;fs.rmSync(cwd,{recursive:true,force:true});}});

test('F2 CLI refuses tampered capsule before network mutation',async()=>{const cwd=fs.mkdtempSync(path.join(os.tmpdir(),'rekt-submit-'));const previous=globalThis.fetch;const seen=[];try{await pull(cwd,capsule(),seen);fs.appendFileSync(path.join(cwd,'.rekt','challenge','CHALLENGE.md'),'tamper\n');globalThis.fetch=async()=>{throw new Error('network_must_not_be_used');};const logs=io();assert.equal(await main(['challenge','submit','--version','1','--artifact-digest',artifactDigest,'--source','0123456789abcdef0123456789abcdef01234567'],{REKT_DEVKIT_TOKEN:'rekt_dk_test'},logs.adapter,cwd),1);assert.equal(logs.err.at(-1),'capsule_file_digest_mismatch:CHALLENGE.md');assert.equal(seen.length,1);}finally{globalThis.fetch=previous;fs.rmSync(cwd,{recursive:true,force:true});}});

test('F2 CLI may infer clean Git HEAD while ignoring .rekt metadata but rejects dirty project source',async()=>{const cwd=fs.mkdtempSync(path.join(os.tmpdir(),'rekt-submit-git-'));const previous=globalThis.fetch;const seen=[];try{execFileSync('git',['init','-q'],{cwd});execFileSync('git',['config','user.email','test@example.invalid'],{cwd});execFileSync('git',['config','user.name','Test Builder'],{cwd});fs.writeFileSync(path.join(cwd,'app.txt'),'v1\n');execFileSync('git',['add','app.txt'],{cwd});execFileSync('git',['commit','-q','-m','initial'],{cwd});const head=execFileSync('git',['rev-parse','HEAD'],{cwd,encoding:'utf8'}).trim().toLowerCase();await pull(cwd,capsule(),seen);let posts=0;globalThis.fetch=async(input,init={})=>{posts+=1;seen.push({input:String(input),init});const body=JSON.parse(String(init.body));assert.equal(body.immutable_source_reference.value,head);return new Response(JSON.stringify(accepted(body)),{status:201,headers:{'content-type':'application/json'}});};let logs=io();assert.equal(await main(['challenge','submit','--version','1','--artifact-digest',artifactDigest,'--api','https://api.test'],{REKT_DEVKIT_TOKEN:'rekt_dk_test'},logs.adapter,cwd),0);assert.equal(posts,1);fs.writeFileSync(path.join(cwd,'app.txt'),'dirty\n');logs=io();assert.equal(await main(['challenge','submit','--version','2','--artifact-digest',artifactDigest,'--api','https://api.test'],{REKT_DEVKIT_TOKEN:'rekt_dk_test'},logs.adapter,cwd),1);assert.equal(logs.err.at(-1),'challenge_submit_dirty_worktree');assert.equal(posts,1);}finally{globalThis.fetch=previous;fs.rmSync(cwd,{recursive:true,force:true});}});
