import './contract-phase7.js';
import {componentSchemas, openapiDocument} from './contract.js';

const schemas = componentSchemas as unknown as Record<string, any>;
const paths = openapiDocument.paths as unknown as Record<string, any>;
const components = openapiDocument.components as unknown as Record<string, any>;
components.securitySchemes.devkitBearer = {type: 'http', scheme: 'bearer', bearerFormat: 'opaque'};
const ref = (name: string) => ({$ref: `#/components/schemas/${name}`});
const errorResponse = (description: string) => ({description, content: {'application/json': {schema: ref('Error')}}});
const bearer = (_scope: string) => [{devkitBearer: []}];

schemas.DevkitScope = {type: 'string', enum: ['player:read','project:read','mission:read','claim:write','update:write','beacon:write','assist:write','ship:prepare']};
schemas.DevkitCredentialClass = {type: 'string', enum: ['CLI','MCP','AUTOMATION']};
schemas.DevkitTokenIssueRequest = {type:'object',additionalProperties:false,required:['request_id','credential_class','label','scopes','expires_in_seconds'],properties:{request_id:ref('RequestId'),credential_class:ref('DevkitCredentialClass'),label:{type:'string',minLength:1,maxLength:80},scopes:{type:'array',minItems:1,maxItems:8,uniqueItems:true,items:ref('DevkitScope')},expires_in_seconds:{type:'integer',minimum:300,maximum:2592000}}};
schemas.DevkitTokenIssuedView = {type:'object',additionalProperties:false,required:['schema_version','token_id','credential_class','label','scopes','token','expires_at'],properties:{schema_version:{type:'string',const:'devkit.token.issued.v1'},token_id:{type:'string',format:'uuid'},credential_class:ref('DevkitCredentialClass'),label:{type:'string'},scopes:{type:'array',items:ref('DevkitScope')},token:{type:'string'},expires_at:{type:'string',format:'date-time'}}};
schemas.DevkitTokenSummaryView = {type:'object',additionalProperties:false,required:['schema_version','token_id','credential_class','label','scopes','created_at','expires_at','revoked_at','last_used_at'],properties:{schema_version:{type:'string',const:'devkit.token.summary.v1'},token_id:{type:'string',format:'uuid'},credential_class:ref('DevkitCredentialClass'),label:{type:'string'},scopes:{type:'array',items:ref('DevkitScope')},created_at:{type:'string',format:'date-time'},expires_at:{type:'string',format:'date-time'},revoked_at:{type:['string','null'],format:'date-time'},last_used_at:{type:['string','null'],format:'date-time'}}};
schemas.DevkitTokenList = {type:'array',items:ref('DevkitTokenSummaryView')};
schemas.DevkitTokenRevokedView = {type:'object',additionalProperties:false,required:['schema_version','token_id','revoked_at'],properties:{schema_version:{type:'string',const:'devkit.token.revoked.v1'},token_id:{type:'string',format:'uuid'},revoked_at:{type:'string',format:'date-time'}}};
schemas.DevkitMissionUpdateRequest = {type:'object',additionalProperties:false,required:['request_id'],minProperties:2,properties:{request_id:ref('RequestId'),current_focus:{type:'string',minLength:1,maxLength:240},next_move:{type:'string',minLength:1,maxLength:240},blocker:{type:['string','null'],maxLength:240},stack_labels:{type:'array',maxItems:8,items:{type:'string',minLength:1,maxLength:40}}}};
schemas.DevkitClaimRequest = {type:'object',additionalProperties:false,required:['request_id','state'],properties:{request_id:ref('RequestId'),state:ref('ParticipantMissionGateState')}};
schemas.DevkitActivityEventView = {type:'object',additionalProperties:false,required:['event_type','occurred_at'],properties:{event_type:{type:'string'},occurred_at:{type:'string',format:'date-time'}}};
schemas.DevkitActivityView = {type:'object',additionalProperties:false,required:['schema_version','project_id','events'],properties:{schema_version:{type:'string',const:'devkit.activity.v1'},project_id:ref('ProjectId'),events:{type:'array',maxItems:50,items:ref('DevkitActivityEventView')}}};
schemas.DevkitHelpBeaconList = {type:'object',additionalProperties:false,required:['schema_version','project_id','beacons'],properties:{schema_version:{type:'string',const:'devkit.help_beacons.v1'},project_id:ref('ProjectId'),beacons:{type:'array',maxItems:1,items:ref('HelpBeaconView')}}};

paths['/v1/devkit/tokens'] = {
  post:{operationId:'issueDevkitToken',security:[{sessionCookie:[]}],requestBody:{required:true,content:{'application/json':{schema:ref('DevkitTokenIssueRequest')}}},responses:{'201':{description:'Issue one scoped DevKit Player credential; raw secret is returned once',content:{'application/json':{schema:ref('DevkitTokenIssuedView')}}},'400':errorResponse('Invalid credential request'),'401':errorResponse('Session required'),'403':errorResponse('Same-origin browser authority required'),'409':errorResponse('Credential issue request already consumed')}},
  get:{operationId:'listDevkitTokens',security:[{sessionCookie:[]}],responses:{'200':{description:'List revocable credential metadata; never returns token hashes or secrets',content:{'application/json':{schema:ref('DevkitTokenList')}}},'401':errorResponse('Session required'),'403':errorResponse('Same-origin browser authority required')}}
};
paths['/v1/devkit/tokens/{tokenId}/revoke'] = {post:{operationId:'revokeDevkitToken',security:[{sessionCookie:[]}],parameters:[{name:'tokenId',in:'path',required:true,schema:{type:'string',format:'uuid'}}],responses:{'200':{description:'Revoke owned DevKit credential',content:{'application/json':{schema:ref('DevkitTokenRevokedView')}}},'401':errorResponse('Session required'),'403':errorResponse('Same-origin browser authority required'),'404':errorResponse('Token not found')}}};
paths['/v1/devkit/me'] = {get:{operationId:'getDevkitMe',security:bearer('player:read'),responses:{'200':{description:'Authenticated Player via scoped DevKit credential',content:{'application/json':{schema:ref('PrivatePlayer')}}},'401':errorResponse('Credential required'),'403':errorResponse('Scope denied'),'429':errorResponse('Rate limited')}}};
paths['/v1/devkit/player/profile'] = {get:{operationId:'getDevkitPlayerProfile',security:bearer('player:read'),responses:{'200':{description:'Authenticated Player profile',content:{'application/json':{schema:ref('PlayerProfileView')}}},'401':errorResponse('Credential required'),'403':errorResponse('Scope denied'),'429':errorResponse('Rate limited')}}};
paths['/v1/devkit/mission/current'] = {
  get:{operationId:'getDevkitCurrentMission',security:bearer('mission:read'),responses:{'200':{description:'Same canonical Command projection used by Web',content:{'application/json':{schema:ref('CommandView')}}},'404':errorResponse('No active Mission'),'429':errorResponse('Rate limited')}},
  patch:{operationId:'updateDevkitCurrentMission',security:bearer('update:write'),requestBody:{required:true,content:{'application/json':{schema:ref('DevkitMissionUpdateRequest')}}},responses:{'200':{description:'Participant Mission update through canonical domain mutation',content:{'application/json':{schema:ref('CommandView')}}},'400':errorResponse('Invalid update'),'403':errorResponse('Scope/authority denied'),'404':errorResponse('No active Mission'),'409':errorResponse('Idempotency conflict'),'429':errorResponse('Rate limited')}}
};
paths['/v1/devkit/mission/current/claims/{gateKey}'] = {post:{operationId:'claimDevkitMilestone',security:bearer('claim:write'),parameters:[{name:'gateKey',in:'path',required:true,schema:ref('MissionGateKey')}],requestBody:{required:true,content:{'application/json':{schema:ref('DevkitClaimRequest')}}},responses:{'200':{description:'Participant claim only; PROVEN is excluded by schema and server truth ceiling',content:{'application/json':{schema:ref('CommandView')}}},'400':errorResponse('Invalid claim'),'403':errorResponse('Truth ceiling/scope denied'),'404':errorResponse('No active Mission'),'409':errorResponse('Idempotency conflict'),'429':errorResponse('Rate limited')}}};
paths['/v1/devkit/project/current'] = {get:{operationId:'getDevkitCurrentProject',security:bearer('project:read'),responses:{'200':{description:'Current canonical Command Project projection',content:{'application/json':{schema:ref('CommandProject')}}},'404':errorResponse('No active Project'),'429':errorResponse('Rate limited')}}};
paths['/v1/devkit/project/current/help-beacons'] = {
  get:{operationId:'listDevkitHelpBeacons',security:bearer('project:read'),responses:{'200':{description:'Current open Help Beacon',content:{'application/json':{schema:ref('DevkitHelpBeaconList')}}},'404':errorResponse('No active Project'),'429':errorResponse('Rate limited')}},
  post:{operationId:'createDevkitHelpBeacon',security:bearer('beacon:write'),requestBody:{required:true,content:{'application/json':{schema:ref('HelpBeaconCreateRequest')}}},responses:{'201':{description:'Create bounded Help Beacon on current canonical Project',content:{'application/json':{schema:ref('HelpBeaconView')}}},'403':errorResponse('Scope/owner denied'),'404':errorResponse('No active Project'),'409':errorResponse('Idempotency/conflict'),'429':errorResponse('Rate limited')}}
};
paths['/v1/devkit/help-beacons/{beaconId}/assists'] = {post:{operationId:'offerDevkitAssist',security:bearer('assist:write'),parameters:[{name:'beaconId',in:'path',required:true,schema:{type:'string',format:'uuid'}}],requestBody:{required:true,content:{'application/json':{schema:ref('AssistOfferCreateRequest')}}},responses:{'201':{description:'Offer bounded Assist',content:{'application/json':{schema:ref('AssistView')}}},'403':errorResponse('Scope/authority denied'),'404':errorResponse('Beacon not found'),'409':errorResponse('Idempotency/conflict'),'429':errorResponse('Rate limited')}}};
paths['/v1/devkit/project/current/activity'] = {get:{operationId:'getDevkitActivity',security:bearer('project:read'),responses:{'200':{description:'Privacy-safe current Project activity summary',content:{'application/json':{schema:ref('DevkitActivityView')}}},'404':errorResponse('No active Project'),'429':errorResponse('Rate limited')}}};
paths['/v1/devkit/mission/current/ship'] = {post:{operationId:'prepareDevkitShip',security:bearer('ship:prepare'),requestBody:{required:true,content:{'application/json':{schema:ref('ShipSubmissionCreateRequest')}}},responses:{'201':{description:'Prepare/submit claimed Ship to existing verifier path; does not approve it',content:{'application/json':{schema:ref('ShipSubmissionPrivateView')}}},'400':errorResponse('Invalid Ship'),'403':errorResponse('Scope/owner denied'),'404':errorResponse('No active Mission'),'409':errorResponse('Ship conflict'),'429':errorResponse('Rate limited')}}};

// Private selector for the existing GitHub installation lifecycle.
schemas.GitHubRepositoryChoice = {type:'object',additionalProperties:false,required:['repository_id','full_name','private'],properties:{repository_id:{type:'string'},full_name:{type:'string'},private:{type:'boolean'}}};
schemas.GitHubRepositoryChoices = {type:'array',items:ref('GitHubRepositoryChoice')};
paths['/v1/github/repositories'] = {get:{operationId:'listGitHubRepositories',security:[{sessionCookie:[]}],responses:{'200':{description:'Active repositories authorized to the current Player; private projection only',content:{'application/json':{schema:ref('GitHubRepositoryChoices')}}},'401':errorResponse('Session required')}}};

schemas.ConnectionContext = {
  type:'object', additionalProperties:false,
  required:['schema_version','player','github','states','source'],
  properties:{
    schema_version:{type:'string',const:'player.connection_context.private.v1'},
    player:ref('ConnectionContextPlayer'), github:ref('ConnectionContextGithub'), states:ref('ConnectionContextStates'), source:ref('ConnectionContextSource'),
  },
};
schemas.ConnectionContextPlayer = {type:'object',additionalProperties:false,required:['player_id','display_name'],properties:{player_id:ref('PlayerId'),display_name:{type:'string'}}};
schemas.ConnectionContextGithub = {type:'object',additionalProperties:false,required:['user_id','login'],properties:{user_id:{type:['string','null']},login:{type:['string','null']}}};
schemas.ConnectionContextStates = {type:'object',additionalProperties:false,required:['signed_in','app_access','repository_authorized','project_linked','observing'],properties:{signed_in:{type:'string',const:'SIGNED_IN'},app_access:{type:'string',enum:['GRANTED','NOT_GRANTED','REVOKED']},repository_authorized:{type:'string',enum:['AUTHORIZED','NOT_AUTHORIZED','REVOKED']},project_linked:{type:'string',enum:['LINKED','NOT_LINKED','ACCESS_REVOKED']},observing:{type:'string',enum:['OBSERVING','NOT_OBSERVING','UNAVAILABLE']}}};
schemas.ConnectionContextSource = {type:'object',additionalProperties:false,required:['repository_id','repository_full_name','visibility','availability','last_observed_at'],properties:{repository_id:{type:['string','null']},repository_full_name:{type:['string','null']},visibility:{type:'string',enum:['NONE','PUBLIC','PRIVATE']},availability:{type:'string',enum:['NONE','AVAILABLE','REVOKED']},last_observed_at:{type:['string','null'],format:'date-time'}}};
paths['/v1/me/connection'] = {get:{operationId:'getMyConnectionContext',security:[{sessionCookie:[]}],responses:{'200':{description:'Private canonical connection context for the shared Instrument shell',content:{'application/json':{schema:ref('ConnectionContext')}}},'401':errorResponse('Session required')}}};

// Owner-private Assist inbox. Keep this schema inline so the generated public SDK surface does not accidentally expose owner-only messages.
const pendingAssistSchema = {type:'object',additionalProperties:false,required:['assist_id','beacon_id','project_id','offered_by_player_id','offered_by_display_name','message','state','offered_at'],properties:{assist_id:{type:'string',format:'uuid'},beacon_id:{type:'string',format:'uuid'},project_id:ref('ProjectId'),offered_by_player_id:ref('PlayerId'),offered_by_display_name:{type:'string'},message:{type:'string'},state:{type:'string',const:'OFFERED'},offered_at:{type:'string',format:'date-time'}}};
const pendingAssistsSchema = {type:'object',additionalProperties:false,required:['schema_version','project_id','assists'],properties:{schema_version:{type:'string',const:'project.pending_assists.private.v1'},project_id:ref('ProjectId'),assists:{type:'array',maxItems:50,items:pendingAssistSchema}}};
paths['/v1/projects/{projectId}/pending-assists'] = {get:{operationId:'getProjectPendingAssists',security:[{sessionCookie:[]}],parameters:[{name:'projectId',in:'path',required:true,schema:ref('ProjectId')}],responses:{'200':{description:'Owner-private OFFERED Assist inbox for one Project',content:{'application/json':{schema:pendingAssistsSchema}}},'400':errorResponse('Invalid Project ID'),'401':errorResponse('Session required'),'403':errorResponse('Project owner required'),'404':errorResponse('Project not found')}}};
