import {randomUUID} from 'node:crypto';import test from 'node:test';import assert from 'node:assert/strict';import {buildApp} from '../../dist/app.js';import {createDatabase} from '../../dist/database.js';import {migrateToLatest} from '../../dist/migrations.js';
const databaseUrl=process.env.DATABASE_URL;if(!databaseUrl)throw new Error('DATABASE_URL is required');const appOrigin=process.env.INKUBATOR_APP_ORIGIN??'http://127.0.0.1:4175';
function cookie(r){const v=Array.isArray(r.headers['set-cookie'])?r.headers['set-cookie'][0]:r.headers['set-cookie'];assert.ok(v);return v.split(';')[0];}async function session(app,name){const r=await app.inject({method:'POST',url:'/v1/dev/session',headers:{origin:appOrigin},payload:{display_name:name}});assert.equal(r.statusCode,201);return{cookie:cookie(r),playerId:r.json().player.player_id};}async function makeProject(app,c){const rounds=await app.inject({method:'GET',url:'/v1/rounds',headers:{cookie:c}});const round=rounds.json().find(r=>r.code==='ROUND_01');await app.inject({method:'POST',url:`/v1/rounds/${round.round_id}/join`,headers:{origin:appOrigin,cookie:c}});const r=await app.inject({method:'POST',url:'/v1/missions',headers:{origin:appOrigin,cookie:c},payload:{request_id:randomUUID(),round_id:round.round_id,project_name:'Tester Moderation',goal:'Get external human evidence safely',ship_condition:'Tester observation recorded',current_focus:'Need tester',next_move:'Request test'}});assert.equal(r.statusCode,201);return{projectId:r.json().project.project_id,missionId:r.json().mission.mission_id};}

test('Phase 5 tester/moderation is deny-by-default, idempotent and never mints PROVEN',async()=>{const db=createDatabase(databaseUrl);await migrateToLatest(db);const app=buildApp({db,appOrigin,allowDevAuth:true,sessionTtlSeconds:3600,github:null});try{const alice=await session(app,`Alice T ${randomUUID().slice(0,5)}`),bob=await session(app,`Bob T ${randomUUID().slice(0,5)}`),carol=await session(app,`Carol T ${randomUUID().slice(0,5)}`),mod=await session(app,`Mod T ${randomUUID().slice(0,5)}`);const ah={origin:appOrigin,cookie:alice.cookie},bh={origin:appOrigin,cookie:bob.cookie},ch={origin:appOrigin,cookie:carol.cookie},mh={origin:appOrigin,cookie:mod.cookie};const {projectId,missionId}=await makeProject(app,alice.cookie);
const comment=await app.inject({method:'POST',url:`/v1/projects/${projectId}/comments`,headers:bh,payload:{request_id:randomUUID(),body:'This looks suspicious but useful.'}});assert.equal(comment.statusCode,201);const commentId=comment.json().comment_id;
const reportReq=randomUUID();const report=await app.inject({method:'POST',url:`/v1/comments/${commentId}/report`,headers:ch,payload:{request_id:reportReq,reason:'ABUSE',detail:'Needs moderator review'}});assert.equal(report.statusCode,201);assert.equal((await app.inject({method:'POST',url:`/v1/comments/${commentId}/report`,headers:ch,payload:{request_id:reportReq,reason:'ABUSE',detail:'Needs moderator review'}})).json().report_id,report.json().report_id);assert.equal((await db.selectFrom('content_reports').selectAll().where('comment_id','=',commentId).execute()).length,1);
const ownerRemove=await app.inject({method:'DELETE',url:`/v1/ops/comments/${commentId}`,headers:ah,payload:{request_id:randomUUID(),reason:'owner is not operator'}});assert.equal(ownerRemove.statusCode,403);await db.insertInto('moderation_operators').values({player_id:mod.playerId,scope:'GLOBAL_MODERATION'}).execute();const removed=await app.inject({method:'DELETE',url:`/v1/ops/comments/${commentId}`,headers:mh,payload:{request_id:randomUUID(),reason:'confirmed moderation removal'}});assert.equal(removed.statusCode,200);assert.equal(removed.json().state,'REMOVED');const comments=await app.inject({method:'GET',url:`/v1/projects/${projectId}/comments`});const removedView=comments.json().comments.find(c=>c.comment_id===commentId);assert.equal(removedView.state,'REMOVED');assert.equal('body'in removedView,false);
assert.equal((await app.inject({method:'POST',url:`/v1/players/${bob.playerId}/block`,headers:ah,payload:{request_id:randomUUID()}})).statusCode,200);const blockedFollow=await app.inject({method:'POST',url:`/v1/players/${alice.playerId}/follow`,headers:bh,payload:{request_id:randomUUID()}});assert.equal(blockedFollow.statusCode,403);assert.equal(blockedFollow.json().error,'social_interaction_blocked');const blockedComment=await app.inject({method:'POST',url:`/v1/projects/${projectId}/comments`,headers:bh,payload:{request_id:randomUUID(),body:'Blocked'}});assert.equal(blockedComment.statusCode,403);
const testReq=await app.inject({method:'POST',url:`/v1/projects/${projectId}/tester-requests`,headers:ah,payload:{request_id:randomUUID(),prompt:'Try onboarding on mobile and report the first failure.'}});assert.equal(testReq.statusCode,201);const testRequestId=testReq.json().test_request_id;const self=await app.inject({method:'POST',url:`/v1/tester-requests/${testRequestId}/results`,headers:ah,payload:{request_id:randomUUID(),outcome:'PASS',summary:'Self test'}});assert.equal(self.statusCode,403);const blockedTest=await app.inject({method:'POST',url:`/v1/tester-requests/${testRequestId}/results`,headers:bh,payload:{request_id:randomUUID(),outcome:'ISSUE_FOUND',summary:'Blocked tester should not write'}});assert.equal(blockedTest.statusCode,403);
assert.equal((await app.inject({method:'DELETE',url:`/v1/players/${bob.playerId}/block`,headers:ah,payload:{request_id:randomUUID()}})).statusCode,200);const resultReq=randomUUID();const result=await app.inject({method:'POST',url:`/v1/tester-requests/${testRequestId}/results`,headers:bh,payload:{request_id:resultReq,outcome:'ISSUE_FOUND',summary:'Primary CTA is hidden below the fold on mobile.'}});assert.equal(result.statusCode,201);const replay=await app.inject({method:'POST',url:`/v1/tester-requests/${testRequestId}/results`,headers:bh,payload:{request_id:resultReq,outcome:'ISSUE_FOUND',summary:'Primary CTA is hidden below the fold on mobile.'}});assert.equal(replay.statusCode,201);assert.equal(replay.json().test_result_id,result.json().test_result_id);assert.equal((await db.selectFrom('external_test_results').selectAll().where('test_request_id','=',testRequestId).execute()).length,1);
const evidence=await db.selectFrom('history_events').selectAll().where('event_type','=','project.external_test.observed').where('subject_id','=',projectId).execute();assert.equal(evidence.length,1);assert.equal(evidence[0].event_family,'evidence');assert.equal(evidence[0].payload.truth_state,'OBSERVED');assert.equal(evidence[0].payload.outcome,'ISSUE_FOUND');const state=await app.inject({method:'GET',url:`/v1/projects/${projectId}/external-tests`});assert.equal(state.statusCode,200);assert.equal(state.json().requests[0].state,'COMPLETED');assert.equal(state.json().results[0].tester.player_id,bob.playerId);
const world=await app.inject({method:'GET',url:'/v1/world/signals'});const signal=world.json().find(s=>s.project_id===projectId&&s.kind==='EXTERNAL_TEST_RECORDED');assert.ok(signal);assert.equal(signal.truth_state,'OBSERVED');assert.equal(JSON.stringify(world.json()).includes('Primary CTA is hidden below the fold'),false);
const opsEvents=await db.selectFrom('history_events').selectAll().where('event_type','=','ops.project_comment.removed').where('subject_id','=',projectId).execute();assert.equal(opsEvents.length,1);assert.equal(opsEvents[0].payload.truth_state,'OBSERVED');assert.equal(JSON.stringify(opsEvents).includes('This looks suspicious but useful.'),false);const gates=await db.selectFrom('mission_gates').selectAll().where('mission_id','=',missionId).execute();assert.equal(gates.every(g=>g.signal_state==='UNKNOWN'),true);const events=await db.selectFrom('history_events').selectAll().where('subject_id','=',projectId).execute();assert.equal(JSON.stringify(events).includes('PROVEN'),false);
}finally{await app.close();await db.destroy();}});
