import {randomUUID} from 'node:crypto';import test from 'node:test';import assert from 'node:assert/strict';import {buildApp} from '../../dist/app.js';import {createDatabase} from '../../dist/database.js';import {migrateToLatest} from '../../dist/migrations.js';import {runOneJob,SHIP_VERIFICATION_JOB_TYPE} from '../../dist/jobs.js';
const databaseUrl=process.env.DATABASE_URL;if(!databaseUrl)throw new Error('DATABASE_URL required');const appOrigin=process.env.INKUBATOR_APP_ORIGIN??'http://127.0.0.1:4175';
function cookie(r){const v=Array.isArray(r.headers['set-cookie'])?r.headers['set-cookie'][0]:r.headers['set-cookie'];assert.ok(v);return v.split(';')[0];}
async function session(app,name){const r=await app.inject({method:'POST',url:'/v1/dev/session',headers:{origin:appOrigin},payload:{display_name:name}});assert.equal(r.statusCode,201);return{cookie:cookie(r),playerId:r.json().player.player_id};}
async function mission(app,cookieValue){const rounds=await app.inject({method:'GET',url:'/v1/rounds',headers:{cookie:cookieValue}});const round=rounds.json().find(r=>r.code==='ROUND_01');await app.inject({method:'POST',url:`/v1/rounds/${round.round_id}/join`,headers:{origin:appOrigin,cookie:cookieValue}});const create=await app.inject({method:'POST',url:'/v1/missions',headers:{origin:appOrigin,cookie:cookieValue},payload:{request_id:randomUUID(),round_id:round.round_id,project_name:'Ship Control',goal:'Ship safely',ship_condition:'Public URL observed and reviewed',current_focus:'Prepare',next_move:'Submit'}});assert.equal(create.statusCode,201);const id=create.json().mission.mission_id,projectId=create.json().project.project_id;for(const state of ['BUILDING','SHIP_READY']){const r=await app.inject({method:'PATCH',url:`/v1/missions/${id}`,headers:{origin:appOrigin,cookie:cookieValue},payload:{request_id:randomUUID(),state}});assert.equal(r.statusCode,200);}return{id,projectId};}

test('Phase 6A submission is owner-only/idempotent and verifier evidence never mints PROVEN',async()=>{const db=createDatabase(databaseUrl);await migrateToLatest(db);const app=buildApp({db,appOrigin,allowDevAuth:true,sessionTtlSeconds:3600,github:null});try{const alice=await session(app,`Alice S ${randomUUID().slice(0,5)}`),bob=await session(app,`Bob S ${randomUUID().slice(0,5)}`);const m=await mission(app,alice.cookie);const ah={origin:appOrigin,cookie:alice.cookie},bh={origin:appOrigin,cookie:bob.cookie};
const denied=await app.inject({method:'POST',url:`/v1/missions/${m.id}/ship-submissions`,headers:bh,payload:{request_id:randomUUID(),title:'Nope',url:'https://example.com/'}});assert.equal(denied.statusCode,403);
const req=randomUUID();const submit=await app.inject({method:'POST',url:`/v1/missions/${m.id}/ship-submissions`,headers:ah,payload:{request_id:req,title:'Working artifact',url:'https://example.com/demo'}});assert.equal(submit.statusCode,201);const submissionId=submit.json().submission_id;
const replay=await app.inject({method:'POST',url:`/v1/missions/${m.id}/ship-submissions`,headers:ah,payload:{request_id:req,title:'Working artifact',url:'https://example.com/demo'}});assert.equal(replay.statusCode,201);assert.equal(replay.json().submission_id,submissionId);
const conflict=await app.inject({method:'POST',url:`/v1/missions/${m.id}/ship-submissions`,headers:ah,payload:{request_id:req,title:'Working artifact',url:'https://example.org/demo'}});assert.equal(conflict.statusCode,409);
const shipJobs=await db.selectFrom('outbox_jobs').selectAll().where('job_type','=',SHIP_VERIFICATION_JOB_TYPE).execute();const job=shipJobs.find(row=>row.payload&&typeof row.payload==='object'&&!Array.isArray(row.payload)&&row.payload.submission_id===submissionId);assert.ok(job);assert.equal(job.state,'pending');
const noClient=await runOneJob(db,{retryBaseMs:100});assert.equal(noClient.status,'retry');assert.equal((await db.selectFrom('ship_verifier_observations').selectAll().where('submission_id','=',submissionId).execute()).length,0);
await db.updateTable('outbox_jobs').set({next_attempt_at:new Date(0)}).where('job_id','=',job.job_id).execute();
const fake={verify:async({submissionId:id,url})=>({schema_version:'ship-verifier.observation.v1',submission_id:id,outcome:'PASS',reason_code:'PUBLIC_HTTPS_OK',final_url:url,http_status:200,duration_ms:42,redirects:0})};
const done=await runOneJob(db,{shipVerifierClient:fake});assert.equal(done.status,'succeeded');const obs=await db.selectFrom('ship_verifier_observations').selectAll().where('submission_id','=',submissionId).executeTakeFirstOrThrow();assert.equal(obs.outcome,'PASS');
const missionRow=await db.selectFrom('missions').select('state').where('mission_id','=',m.id).executeTakeFirstOrThrow();assert.equal(missionRow.state,'SUBMITTED');const gates=await db.selectFrom('mission_gates').selectAll().where('mission_id','=',m.id).execute();assert.equal(gates.every(g=>g.signal_state==='UNKNOWN'),true);
const evidence=await db.selectFrom('history_events').selectAll().where('event_type','=','project.ship_verifier.observed').where('subject_id','=',m.projectId).execute();assert.equal(evidence.length,1);assert.equal(evidence[0].payload.truth_state,'OBSERVED');assert.equal(JSON.stringify(evidence).includes('PROVEN'),false);assert.equal(JSON.stringify(evidence).includes('SHIPPED'),false);
const publicState=await app.inject({method:'GET',url:`/v1/projects/${m.projectId}/ship`});assert.equal(publicState.statusCode,200);assert.equal(publicState.json().latest_submission.state,'OBSERVED');assert.equal(publicState.json().latest_submission.verifier_observation.outcome,'PASS');
}finally{await app.close();await db.destroy();}});
