export {
  SCALE_CONTROL_LOSS_LIMIT_BPS,
  SCALE_CONTROL_TRADE_TARGET,
  STOP_LOSS_TRADE_TARGET,
  STOP_PLAN_WINDOW_MS,
  RISK_SIZING_TRADE_TARGET,
  RISK_SIZING_PARTIAL_EXIT_TARGET,
} from './qualification.js';

export const CAREER_TUNING_VERSION = 'CAREER_TUNING_V0_PROVISIONAL';
