import fs from 'node:fs';
import path from 'node:path';
import {compilePublicState} from '../../packages/inkubator-protocol/src/index.mjs';

const root = process.cwd();
const fixtureRoot = path.join(root, 'content', 'inkubator', 'fixtures');
const outputPath = path.join(root, 'apps', 'inkubator-lab', 'src', 'generated', 'inkubator-state.ts');

function readJson(name) {
  return JSON.parse(fs.readFileSync(path.join(fixtureRoot, name), 'utf8'));
}

const state = compilePublicState({
  mode: 'development-fixture',
  rounds: [readJson('round.dev.json')],
  players: [readJson('player.dev.json')],
  receipts: [readJson('receipt.dev.json')],
});

fs.mkdirSync(path.dirname(outputPath), {recursive: true});
const source = `// GENERATED by scripts/inkubator/compile-state.mjs. Do not hand edit.\nexport const inkubatorState = ${JSON.stringify(state, null, 2)} as const;\n`;
fs.writeFileSync(outputPath, source, 'utf8');
console.log(`Compiled Inkubator public state -> ${path.relative(root, outputPath)}`);
